version: '3.1'
services:
  postgresql:
    image: postgres:latest
    ports:
      - '8080:8080'
    volumes:
      - ./data:/var/lib/postgres/data
    environment:
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=mypassword

volumes:
  data:
    driver: local